export interface ModelPromptPreset {
  workflowFile: string;
  promptTemplate: string;
  caption: string;
  qualityTags: string[];
  negativeTags: string[];
  selectionTagOverrides?: Record<string, Record<string, string[]>>;
  selectionNegativeTagOverrides?: Record<string, Record<string, string[]>>;
}

const COMMON_QUALITY_TAGS = [
  "official art",
  "anime coloring",
  "soft shading",
  "polished shading",
  "stable anatomy",
  "detailed face",
  "detailed eyes",
  "detailed hands",
  "detailed feet",
  "full body",
  "head to toe",
  "both feet visible",
];

const COMMON_NEGATIVE_TAGS = [
  "lowres",
  "blurry",
  "jpeg artifacts",
  "bad anatomy",
  "bad proportions",
  "bad face",
  "bad eyes",
  "bad hands",
  "malformed hands",
  "bad fingers",
  "extra fingers",
  "missing fingers",
  "fused fingers",
  "extra digits",
  "fewer digits",
  "bad feet",
  "cropped",
  "out of frame",
  "cropped feet",
  "feet out of frame",
  "hands out of frame",
  "cowboy shot",
  "medium shot",
  "face focus",
  "upper body",
  "lower body only",
  "legs focus",
  "legs shot",
  "from below",
  "low angle shot",
  "worm's eye view",
  "extra arms",
  "extra legs",
  "extra limbs",
  "chibi",
  "super deformed",
  "spoken question mark",
  "duplicate person",
  "multiple people",
  "2girls",
  "group",
  "multiple views",
  "reference sheet",
  "character sheet",
  "text",
  "watermark",
  "signature",
  "distorted feet",
  "nsfw",
  "loli",
  "child",
  "teen",
  "teenager",
  "young-looking",
  "underage",
  "minor",
  "childlike",
];

const SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES = {
  bodyType: {
    slender: ["chubby", "overweight", "thick body"],
    athletic: ["chubby", "overweight"],
    average: ["very skinny", "chubby", "overweight", "muscular body"],
    plump: ["skinny", "slim", "thin body"],
  },
  breastSize: {
    subtle: ["medium breasts", "large breasts", "huge breasts", "busty"],
    small: ["large breasts", "huge breasts", "busty"],
    medium: ["flat chest", "huge breasts"],
    large: ["flat chest", "small breasts", "huge breasts"],
    prominent: ["flat chest", "small breasts"],
  },
  hipSize: {
    small: ["wide hips", "thick thighs", "big thighs", "heavy thighs"],
    medium: ["narrow hips", "wide hips", "thick thighs", "curvy"],
    large: ["narrow hips"],
    prominent: ["narrow hips"],
  },
};

const PONY_FORM_SELECTION_NEGATIVE_OVERRIDES = {
  ...SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES,
  breastSize: {
    ...SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES.breastSize,
    subtle: [
      "medium breasts",
      "large breasts",
      "huge breasts",
      "big breasts",
      "large chest",
      "huge chest",
      "busty",
      "cleavage",
    ],
    small: [
      "large breasts",
      "huge breasts",
      "big breasts",
      "large chest",
      "huge chest",
      "busty",
      "cleavage",
    ],
  },
  hipSize: {
    ...SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES.hipSize,
    medium: [
      "narrow hips",
      "wide hips",
      "huge hips",
      "oversized hips",
      "exaggerated hips",
      "thick thighs",
      "pear-shaped body",
      "curvy",
    ],
  },
};

export const modelPromptPresets: Record<string, ModelPromptPreset> = {
  "illustrious-xl": {
    workflowFile: "workflow_illustrious_xl_v2.json",
    promptTemplate:
      'You are a professional anime illustrator and art director. Generate a polished high-quality anime image with the highest degree of image-text alignment based on XML-format textual prompts. <Prompt Start>\n{\n"character_1": {\n"bbox": [\n0,\n0,\n1000,\n1000\n],\n"name": "$character_1$"\n},\n"image": {\n"quality_tags": "{quality_prompt}",\n"customization_tags": "\n{user_prompt}\n",\n"caption": "{caption}"\n}\n}',
    caption:
      "A finished anime-style full-body illustration of one woman standing naturally. The character is fully visible from head to toe, centered in frame, with both feet visible. The image is one complete polished color illustration with stable anatomy, detailed face and eyes, a clean silhouette, and natural readable hands and fingers.",
    qualityTags: [
      "masterpiece",
      "best quality",
      "good quality",
      "highres",
      "absurdres",
      "finished color artwork",
      ...COMMON_QUALITY_TAGS,
      "natural hands",
      "five fingers on each hand",
      "separated fingers",
      "relaxed fingers",
      "fully clothed",
    ],
    negativeTags: [
      "worst quality",
      "bad quality",
      "low quality",
      "average quality",
      "displeasing",
      "very displeasing",
      "comic",
      "scan artifacts",
      "jaggy lines",
      "unclear",
      "noisy",
      "grainy",
      "compression artifacts",
      "messy lineart",
      "sketch",
      "sketchy",
      "rough sketch",
      "unfinished",
      "monochrome",
      "greyscale",
      "flat colors",
      "bad body",
      "deformed body",
      "malformed body",
      "distorted body",
      "long torso",
      "short torso",
      "twisted torso",
      "deformed face",
      "asymmetrical face",
      "misaligned eyes",
      "bad mouth",
      "poorly drawn hands",
      "deformed hands",
      "distorted hands",
      "bad hand anatomy",
      "malformed fingers",
      "unnatural fingers",
      "long fingers",
      "short fingers",
      "broken fingers",
      "duplicated fingers",
      "too many fingers",
      "bad finger count",
      "missing knuckles",
      "bad thumbs",
      "malformed feet",
      "malformed limbs",
      "missing limbs",
      "extra arms",
      "extra legs",
      "disconnected limbs",
      "close-up",
      "bust shot",
      "upper body only",
      "lower body only",
      "cropped legs",
      "head out of frame",
      "extra person",
      "alternate view",
      "side view",
      "back view",
      "model sheet",
      "turnaround",
      "alternate outfit",
      "outfit comparison",
      "inconsistent outfit",
      "letters",
      "words",
      "labels",
      "annotations",
      "logo",
      "hidden hands",
      "complex hand gesture",
      "unclear hands",
      "obscured fingers",
      ...COMMON_NEGATIVE_TAGS,
    ],
    selectionNegativeTagOverrides: SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES,
  },
  "pony-v6": {
    workflowFile: "workflow_pony_v6.json",
    promptTemplate:
      "You are a professional anime illustrator and art director. Generate a high-quality anime image with the highest degree of image-text alignment based on XML-format textual prompts. <Prompt Start>\n<prompt>\n<always_on_pony_quality_tags>\n{quality_prompt}\n</always_on_pony_quality_tags>\n\n{user_prompt}\n\n<caption_tags>\n{caption}\n</caption_tags>\n</prompt>",
    caption:
      "A finished anime-style full-body character design of one woman standing naturally in a modest, fully clothed outfit. The character is centered in frame and fully visible from head to toe, with both feet visible, stable anatomy, a clean silhouette, detailed face and eyes, and natural readable hands.",
    qualityTags: [
      "score_9",
      "score_8_up",
      "score_7_up",
      // "score_6_up",
      "source_anime",
      "rating_safe",
      "high quality",
      "anime girl",
      "two arms",
      "two legs",
      ...COMMON_QUALITY_TAGS,
      "natural hands",
      "correct finger anatomy",
      "five fingers on each hand",
      "natural thumbs",
      "separated fingers",
      "relaxed fingers",
      "fully clothed",
      "modest outfit",
      "non-revealing clothing",
      "no text",
      "no labels",
      "no annotations",
    ],
    negativeTags: [
      "score_4",
      "score_3",
      "score_2",
      "score_1",
      "rating_questionable",
      "rating_explicit",
      "worst quality",
      "low quality",
      "(bad hands:1.35)",
      "(malformed hands:1.35)",
      "(bad hand anatomy:1.35)",
      "(bad fingers:1.45)",
      "(extra fingers:1.5)",
      "(missing fingers:1.5)",
      "(fused fingers:1.4)",
      "(broken fingers:1.35)",
      "(extra digits:1.45)",
      "(fewer digits:1.45)",
      "bad thumbs",
      "(extra arms:1.5)",
      "(extra legs:1.5)",
      "(extra limbs:1.5)",
      "(missing arms:1.3)",
      "(missing legs:1.3)",
      "(disconnected limbs:1.4)",
      "(malformed limbs:1.4)",
      "source_real",
      "source_furry",
      "source_cartoon",
      "realistic",
      "photorealistic",
      "photography",
      "3d",
      "pony",
      "anthro",
      "feral",
      "my little pony",
      "equine",
      "furry",
      "bikini",
      "swimsuit",
      "lingerie",
      "underwear",
      "cleavage",
      "exposed midriff",
      "skimpy outfit",
      "revealing clothes",
      "see-through clothing",
      "leotard",
      ...COMMON_NEGATIVE_TAGS,
    ],
    selectionTagOverrides: {
      breastSize: {
        subtle: ["flat chest", "small chest", "petite chest"],
        small: ["small breasts", "modest breasts", "small chest"],
      },
      hipSize: {
        medium: ["average hips", "proportional hips"],
      },
      clothingStyle: {
        "sci-fi": ["covered outfit"],
      },
    },
    selectionNegativeTagOverrides: PONY_FORM_SELECTION_NEGATIVE_OVERRIDES,
  },
  "animagine-xl-v3": {
    workflowFile: "workflow_animagine_xl.json",
    promptTemplate:
      "You are a professional anime illustrator and art director. Generate a high-quality anime image with the highest degree of image-text alignment based on XML-format textual prompts. <Prompt Start>\n<prompt>\n{user_prompt}\n\n<caption_tags>\n{caption}\n</caption_tags>\n\n<quality_suffix>\n{quality_prompt}\n</quality_suffix>\n</prompt>",
    caption:
      "A finished anime-style full-body portrait of one woman standing naturally. The character is centered in frame and fully visible from head to toe, with both feet visible, stable anatomy, a clean silhouette, detailed face and eyes, and natural readable hands.",
    qualityTags: [
      "masterpiece",
      "high score",
      // "great score",
      "absurdres",
      ...COMMON_QUALITY_TAGS,
      "correct finger anatomy",
      "five fingers on each hand",
      "natural thumbs",
    ],
    negativeTags: [
      "worst quality",
      "low quality",
      "bad score",
      // "average score",
      ...COMMON_NEGATIVE_TAGS.filter((tag) => tag !== "feet out of frame"),
    ],
    selectionNegativeTagOverrides: SIMPLE_FORM_SELECTION_NEGATIVE_OVERRIDES,
  },
};
